export const testimonialsData = [
  {
    id: 1,
    rating: 4,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 2,
    rating: 5,
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 3,
    rating: 4,
    text: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 4,
    rating: 5,
    text: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 5,
    rating: 3,
    text: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 6,
    rating: 4,
    text: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 7,
    rating: 5,
    text: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 8,
    rating: 4,
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
  {
    id: 9,
    rating: 5,
    text: "Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.",
    name: "Matthew Ward",
    avatar: "/images/dummy-images/testimonialUser.png",
  },
];
