import "bootstrap/dist/css/bootstrap.min.css";
import "react-phone-input-2/lib/style.css";
import "react-modern-drawer/dist/index.css";
import "./css/global.css";
import "./css/typography.css";
import "./css/color.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Header from "@/component/organisms/Header";
import Footer from "@/component/organisms/Footer";
import { CustomProvider } from "@/store/customProvider";
import { SocketProvider } from "@/context/SocketContext";
import ToastHandler from "@/component/atoms/ToastHandler";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <CustomProvider>
          <SocketProvider>
            <ToastHandler />
            {children}
          </SocketProvider>
        </CustomProvider>
      </body>
    </html>
  );
}

